name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: write
  contents: write

env:
  NODE_AUTH_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npm run build

      - run :  git config --global user.email "manuel.aguilar.rocha@live.com"
      - run :  git config --global user.name "Manuel Aguilar"

      #- run: npm run release
      #  env: 
      #    GITHUB_TOKEN: ${{ github.token }}

      #- name: release
      #  uses: actions/create-release@v1
      #  id: create_release
      #  with:
      #    draft: false
      #    prerelease: false
      #    release_name: ${{ github.ref }}
      #    tag_name: ${{ github.ref }}
      #    body_path: CHANGELOG.md
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
              name: build-artifact
              path: dist
      
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v3
        with: version: '*'

      - name: Push a package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v3
        env:
          OCTOPUS_URL: 'https://maguilar.octopus.app'
          OCTOPUS_API_KEY: 'API-9IU982VHYT7CGZYEDSNHKBKGRSZR1ZF'
          OCTOPUS_SPACE: 'Default'
        with:
          packages:
             build-artifact.zip 
